Updated workflows
https://github.com/navikt/crm-workflows-base/releases/tag/v1.2

diff --git a/.github/workflows/pull-request_validation.yml b/.github/workflows/pull-request_validation.yml
--- a/.github/workflows/pull-request_validation.yml
+++ b/.github/workflows/pull-request_validation.yml
@@ -1,5 +1,5 @@
 # Unique name for this workflow
-name: "[Pull Request] Validate Metadata"
+name: "[PR] Validate"
 
 # Definition when the workflow should run
 on:
@@ -8,42 +8,45 @@ on:
       - "*"
 
 jobs:
-  validate:
+  # ######################################## #
+  # ############### COMPILE ################ #
+  # ######################################## #
+  setup:
+    name: Setup
     runs-on: ubuntu-latest
     steps:
-      # Install Salesforce CLI
-      - name: Install Salesforce CLI
-        run: |
-          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
-          mkdir sfdx-cli
-          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
-          ./sfdx-cli/install
+      # Install SFDX
+      - name: Install SFDX
+        uses: sfdx-actions/setup-sfdx@v1
 
       # Checkout the code in the pull request
       - name: "Checkout source code"
         uses: actions/checkout@v2
 
-      # Store secret for dev hub
-      - name: "Populate auth file with PROD_SFDX_URL secret"
-        shell: bash
-        run: "echo ${{ secrets.PROD_SFDX_URL}} > ./PROD_SFDX_URL.txt"
-
       # Authenticate dev hub
       - name: "Authenticate Dev Hub"
-        run: "sfdx force:auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a devhub -d"
-
-      # Remove auth files
-      - name: "Remove auth files"
-        if: always()
-        run: "rm -f ./PROD_SFDX_URL.txt"
-
-      # Delete unpackagable
-      - name: "Delete unpackagable"
-        run: rm -rf unpackagable
+        run: |
+          echo ${{ secrets.PROD_SFDX_URL}} > ./PROD_SFDX_URL.txt
+          sfdx force:auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a devhub -d
+          rm -f ./PROD_SFDX_URL.txt
 
       # Create scratch org
       - name: "Create scratch org"
         run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
+
+      # Set SCRATCH_ORG_SFDX_AUTH_URL.txt
+      # ! saves sfdx auth url as artifact to circumvent GitHub Actions censoring of the value (which occurs when used with job output)
+      # ! artifact is later deleted
+      - name: "Set SCRATCH_ORG_SFDX_AUTH_URL.txt"
+        id: set-auth-url
+        run: sfdx force:org:display -u scratch-org --verbose --json | jq '.result.sfdxAuthUrl' | sed 's/\"//g' > SCRATCH_ORG_SFDX_AUTH_URL.txt
+
+      # Upload SCRATCH_ORG_SFDX_AUTH_URL.txt
+      - name: Upload SFDX AuthUrl
+        uses: actions/upload-artifact@v2
+        with:
+          name: sfdx-auth-url
+          path: SCRATCH_ORG_SFDX_AUTH_URL.txt
 
       # Install sfpowerkit plugin used to install multiple packages only by version number
       - name: "Install sfpowerkit plugin"
@@ -55,7 +58,7 @@ jobs:
         run: |
           keys=""
           for p in $(jq '.result | .[].Name' -r <<< "$(sfdx force:package:list --json)"); do
-              keys+=$p":${{ secrets.PACKAGE_KEY}} "
+              keys+=$p":${{ secrets.PACKAGE_KEY }} "
           done
 
           echo "::set-output name=keys::$(echo $keys)"
@@ -64,65 +67,151 @@ jobs:
       - name: "Install dependant packages"
         run: "sfdx sfpowerkit:package:dependencies:install -u scratch-org -r -a -w 60 -k '${{ steps.install-keys.outputs.keys }}'"
 
+  compile:
+    name: Compile Metadata
+    needs: setup
+    runs-on: ubuntu-latest
+    steps:
+      # Install SFDX
+      - name: Install SFDX
+        uses: sfdx-actions/setup-sfdx@v1
+
+      # Checkout the code in the pull request
+      - name: "Checkout source code"
+        uses: actions/checkout@v2
+
+      # Download SCRATCH_ORG_SFDX_AUTH_URL.txt
+      - name: Download SCRATCH_ORG_SFDX_AUTH_URL.txt
+        uses: actions/download-artifact@v2
+        with:
+          name: sfdx-auth-url
+
+      # Authenticate scratch org
+      - name: "Authenticate scratch org"
+        run: sfdx force:auth:sfdxurl:store -f ./SCRATCH_ORG_SFDX_AUTH_URL.txt -a scratch-org -s
+
       # Deploy source to scratch org
       - name: "Push source to scratch org"
         run: "sfdx force:source:push"
 
-      # Sleep for 1 minute while permset groups are updating
-      - name: Sleep for 1 minute while permset groups are updating
-        uses: jakejarvis/wait-action@master
+  # ######################################## #
+  # ############### RUN TESTS ############## #
+  # ######################################## #
+  run-tests:
+    name: Run Apex Tests
+    needs: compile
+    runs-on: ubuntu-latest
+    steps:
+      # Install SFDX
+      - name: Install SFDX
+        uses: sfdx-actions/setup-sfdx@v1
+
+      # Checkout the code in the pull request
+      - name: "Checkout source code"
+        uses: actions/checkout@v2
+
+      # Download SCRATCH_ORG_SFDX_AUTH_URL.txt
+      - name: Download SCRATCH_ORG_SFDX_AUTH_URL.txt
+        uses: actions/download-artifact@v2
         with:
-          time: "1m"
+          name: sfdx-auth-url
+
+      # Authenticate scratch org
+      - name: "Authenticate scratch org"
+        run: sfdx force:auth:sfdxurl:store -f ./SCRATCH_ORG_SFDX_AUTH_URL.txt -a scratch-org -s
+
+      # Get all test classes from current repo
+      - name: Get all test classes from current repo
+        id: test-classes-in-repo
+        run: |
+          classes=""
+          for p in $( grep -r -l -i --include="*.cls" "@istest" . | sed 's@.*/@@' ); do
+            classes+=$(echo $p | cut -f 1 -d '.')","
+          done
+          echo "::set-output name=classes::$( echo $classes | sed 's/\(.*\),/\1 /' )"
 
       # Run Apex tests in scratch org
       - name: "Run Apex tests"
-        # run: "sfdx force:apex:test:run -l RunLocalTests -c -r human -d ./tests/apex -w 30"
-        run: sfdx force:source:deploy -m ApexClass --testlevel=RunLocalTests --checkonly
+        run: "sfdx force:apex:test:run -t ${{ steps.test-classes-in-repo.outputs.classes }} -c -r human -d ./tests/apex -w 20"
 
-      # Create users
-      - name: "Create users"
-        if: contains( github.event.pull_request.labels.*.name, 'saveScratchOrg')
-        id: create-users
+      # Upload Apex test results
+      - name: Upload Apex test results
+        uses: actions/upload-artifact@v2
+        with:
+          name: apex-tests
+          path: ./tests/apex
+
+  # ######################################## #
+  # ########## CHECK CODE COVERAGE ######### #
+  # ######################################## #
+  check-code-coverage:
+    name: Validate 85% Code Coverage
+    needs: run-tests
+    runs-on: ubuntu-latest
+    steps:
+      # Checkout the code in the pull request
+      - name: "Checkout source code"
+        uses: actions/checkout@v2
+
+      # Download tests
+      - name: Download tests
+        uses: actions/download-artifact@v2
+        with:
+          name: apex-tests
+          path: ./tests/apex
+
+      # Validate at least 85% code coverage
+      - name: Validate at least 85% code coverage
         run: |
-          sfdx force:user:create -f config/users/pull_request.json -u scratch-org -a employee
-          echo "::set-output name=loginUrl::$(sfdx force:user:password:generate --onbehalfof=scratch-org)"
+          codecoverage=$(cat tests/apex/test-result-707*.json | jq '.summary.orgWideCoverage' | sed 's/\"//g; s/\%//g')
+          if [ $codecoverage -lt 85 ]
+          then
+            echo "Code coverage is $codecoverage%"
+            echo "Because it is less than 85%, the validation failed"
+            exit 125
+          fi
 
-          admin=$(sfdx force:user:display -u scratch-org --json)
-          employee=$(sfdx force:user:display -u employee --json)
+  # ######################################## #
+  # ################ CLEANUP ############### #
+  # ######################################## #
+  cleanup:
+    name: Cleanup
+    needs: [setup, compile, run-tests, check-code-coverage]
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      # Install SFDX
+      - name: Install SFDX
+        uses: sfdx-actions/setup-sfdx@v1
 
-          echo "::set-output name=instanceUrl::$( echo $admin | jq -r '.result.instanceUrl' )"
+      # Checkout the code in the pull request
+      - name: "Checkout source code"
+        uses: actions/checkout@v2
 
-          echo "::set-output name=adminUsername::$( echo $admin | jq -r '.result.username' )"
-          echo "::set-output name=adminPassword::$( echo $admin | jq -r '.result.password' )"
-          echo "::set-output name=adminInstantLogin::$( sfdx force:org:open -u scratch-org -r --json | jq -r '.result.url' )"
+      # Authenticate dev hub
+      - name: "Authenticate Dev Hub"
+        run: |
+          echo ${{ secrets.PROD_SFDX_URL}} > ./PROD_SFDX_URL.txt
+          sfdx force:auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a devhub -d
+          rm -f ./PROD_SFDX_URL.txt
 
-          echo "::set-output name=employeeUsername::$( echo $employee | jq -r '.result.username' )"
-          echo "::set-output name=employeePassword::$( echo $employee | jq -r '.result.password' )"
-          echo "::set-output name=employeeInstantLogin::$( sfdx force:org:open -u employee -r --json | jq -r '.result.url' )"
+      # Download SCRATCH_ORG_SFDX_AUTH_URL.txt
+      - name: Download SCRATCH_ORG_SFDX_AUTH_URL.txt
+        uses: actions/download-artifact@v2
+        with:
+          name: sfdx-auth-url
 
-      # Slack Notification
-      - name: "Slack Notification"
-        if: contains( github.event.pull_request.labels.*.name, 'saveScratchOrg')
-        uses: rtCamp/action-slack-notify@v2.0.0
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          SLACK_USERNAME: "Scratch Organization Aficionado"
-          SLACK_MESSAGE: |
-            *Login to Scratch Org*
+      # Authenticate scratch org
+      - name: "Authenticate scratch org"
+        run: sfdx force:auth:sfdxurl:store -f ./SCRATCH_ORG_SFDX_AUTH_URL.txt -a scratch-org -s
 
-            URL: ${{steps.create-users.outputs.instanceUrl}}
-
-            *Admin User:*
-            Username: ${{ steps.create-users.outputs.adminUsername }}
-            Password: ${{ steps.create-users.outputs.adminPassword }} (valid for 24 hours)
-            Instant login: ${{ steps.create-users.outputs.adminInstantLogin }} (valid for 2 hours)
-
-            *NAV Employee User:*
-            Username: ${{ steps.create-users.outputs.employeeUsername }}
-            Password: ${{ steps.create-users.outputs.employeePassword }} (valid for 24 hours)
-            Instant login: ${{ steps.create-users.outputs.employeeInstantLogin }} (valid for 2 hours)
+      # Delete SCRATCH_ORG_SFDX_AUTH_URL.txt
+      - name: Delete SCRATCH_ORG_SFDX_AUTH_URL.txt
+        uses: geekyeggo/delete-artifact@v1
+        with:
+          name: sfdx-auth-url
 
       # Delete scratch orgs
       - name: "Delete scratch org"
-        if: failure() || !contains( github.event.pull_request.labels.*.name, 'saveScratchOrg')
+        if: always()
         run: "sfdx force:org:delete -p -u scratch-org"
